### ISSUE TITLE
thumbデータを入れても画像が表示されない

### ISSUE THREAD

**Issue by kumakamikoubou** [kumakamikoubou/DTXmatixx#13]
ツイッターから。

**Comment by kumakamikoubou** [comment]
set.def を使った場合、set.def と同じ場所にthumbデータを入れれば表示されるよう修正しました。
また、set.def を使わない場合についても表示されることを確認しました。

**Comment by limyz** [comment]
ce1775b5b6f46ddc5bed796c6358756bdee260f4 を参照してください。
